# OB_GINS: Optimization-Based GNSS/INS Integrated Navigation System

# integration scheme
scheme: 2 # 1: loose 2: tight
imu_type: 3 # 1: dji_imu 2: openlog 3: i300
INS_only: false
is_NHC: false

# 数据文件
# Data files
imufile: "dataset/simu/IMU_simu.txt"
vlpfile: "dataset/simu/VLP_simu.txt"
outputpath: "dataset/simu/"

# 时间信息, s
# Processing time parameters
#####
windows: 5
starttime: 0
endtime: 19

# 初始化信息
# Initialization parameters
initcoordinate: [31.4833,114.3502,28]
initpos: [2.5,4.5,0] # bug, should be NED, not NEU
initvel: [3,0,-0.1]  # 北东地速度 (NED velocity), m/s
initatt: [0,0,0]     # 横滚俯仰航向 (RPY attitude), deg

# IMU初始误差
# IMU constant biases
initgb: [0,0,0]  # 初始陀螺零偏 (gyroscope biases), deg/hr
initab: [0,0,0]  # 初始加表零偏 (accelerometer biases), mGal

# IMU原始数据频率, Hz
# IMU data rate
imudatarate: 100

# 安装参数
# Installation parameters
antlever: [ 0, 0, 0 ]  # 天线杆臂 (antenna lever), IMU前右下方向, m
odolever: [ 0, 0, 0 ]  # 里程计杆臂 (odometer lever), IMU前右下方向, m
bodyangle: [ 0, 0, 0 ] # IMU到载体的旋转角 (mouting angles to construct C_b^v), deg

odometer:
    isuseodo: false             # use odometer

    std: [ 0.05, 0.05, 0.05 ]   # 里程标准差 (vehicle velocity standard deviation), m/s
    srw: 100                    # 比例因子误差 (odometer scale-factor standard deviation), PPM

# IMU噪声建模参数
# IMU noise parameters
#####
imumodel:
    arw: 0.015     # deg/sqrt(hr)
    vrw: 0.01    # m/s/sqrt(hr)
    gbstd: 0.5   # deg/hr
    abstd: 10   # mGal
    #arw: 0.015     # deg/sqrt(hr)
    #vrw: 0.01    # m/s/sqrt(hr)
    #gbstd: 0.5   # deg/hr
    #abstd: 10   # mGal
    corrtime: 1.0 # hr
    
# vlp parameters
#####
NLED: 5
vlp_corr: true
LED: [0,0,5,5,0,5,2.5,2.5,5,5,5,5,0,5,5]
emission_power: [500, 500, 500, 500, 500]
lamber_coef: [1,1,1,1,1]
err: [0.05,0.05,0.05]

# vlp仿真中断配置
# vlp outage parameters
isuseoutage: false
outagetime: 0
outagelen: 60
outageperiod: 180

# 固定阈值GNSS抗差 (m)
# a fixed threshold for VLP outlier-culling using positioning standard deviation
vlpthreshold: 20
